version: "3.9"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - .env
    environment:
      - ENV=development

  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - ENV=production

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    working_dir: /app
    command: ["python", "-m", "pytest", "tests"]
    environment:
      - ENV=test
      - REDIS_ENABLED=false
    env_file:
      - .env
    
  redis:
    image: redis:7.2-alpine
    container_name: cache_redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass \"$REDIS_PASSWORD\""]
