version: "3.9"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
    environment:
      - ENV=development

  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - ENV=production

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    command: ["pytest", "tests"]
    environment:
      - ENV=test